// T6 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool
#include common_scripts\utility;
#include maps\mp\_utility;
#include maps\mp\zombies\_zm_stats;

main()
{
    printf( "[EETrackerT6] {\"schemaVersion\":1,\"type\":\"observer_loaded\",\"game\":\"bo2\",\"map\":\"zm_highrise\",\"source\":\"gsc\"}\n" );
}

init()
{
    level thread ee_tracker_highrise_monitor();
    level thread ee_tracker_highrise_watch_inventory();
}

ee_tracker_highrise_watch_inventory()
{
    level endon( "end_game" );
    level.ee_tracker_inventory_signatures = [];

    while ( true )
    {
        players = get_players();

        for ( i = 0; i < players.size; i++ )
            players[i] thread ee_tracker_highrise_inventory_if_changed( i );

        wait 1;
    }
}

ee_tracker_highrise_inventory_if_changed( slot )
{
    items = "";
    weapons = self getweaponslist();

    for ( i = 0; i < weapons.size; i++ )
        if ( weapons[i] == "slipgun_zm" || weapons[i] == "slipgun_upgraded_zm" || weapons[i] == "galvaknuckles_zm" || weapons[i] == "knife_ballistic_zm" )
            items = items + weapons[i] + "|";

    if ( isdefined( level.ee_tracker_inventory_signatures[slot] ) && level.ee_tracker_inventory_signatures[slot] == items )
        return;

    level.ee_tracker_inventory_signatures[slot] = items;
    printf( "[EETrackerT6] {\"schemaVersion\":1,\"type\":\"player_inventory\",\"game\":\"bo2\",\"map\":\"zm_highrise\",\"sessionId\":\"" + level.ee_tracker_highrise_session + "\",\"playerSlot\":" + slot + ",\"inventoryItems\":\"" + items + "\",\"source\":\"gsc\"}\n" );
}

ee_tracker_highrise_monitor()
{
    level endon( "end_game" );
    level.ee_tracker_highrise_session = randomint( 1000000000 );
    level.ee_tracker_highrise_stage = "";
    level.ee_tracker_highrise_started = 0;
    level.ee_tracker_highrise_route_locked = 0;
    level.ee_tracker_highrise_elevator_progress = -1;
    level.ee_tracker_highrise_ball_progress = -1;
    level.ee_tracker_highrise_ball_stage_seen = 0;
    level thread ee_tracker_highrise_watch_complete();
    printf( "[EETrackerT6] {\"schemaVersion\":1,\"type\":\"session_started\",\"game\":\"bo2\",\"map\":\"zm_highrise\",\"sessionId\":\"" + level.ee_tracker_highrise_session + "\",\"source\":\"gsc\"}\n" );

    while ( true )
    {
        stage = "";

        if ( isdefined( level._last_stage_started ) )
            stage = level._last_stage_started;

        if ( stage != level.ee_tracker_highrise_stage )
        {
            previous = level.ee_tracker_highrise_stage;
            level.ee_tracker_highrise_stage = stage;

            if ( stage == "atd" && !level.ee_tracker_highrise_started )
            {
                level.ee_tracker_highrise_started = 1;
                ee_tracker_highrise_signal( "bo2.highrise.started" );
            }

            if ( previous == "slb" )
                ee_tracker_highrise_signal( "bo2.highrise.shared.dragon_balls" );

            if ( previous != "" )
                ee_tracker_highrise_stage_complete( previous );
        }

        if ( flag( "sq_atd_elevator_activated" ) )
            ee_tracker_highrise_signal_once( "elevators", "bo2.highrise.shared.elevators" );

        if ( flag( "sq_atd_drg_puzzle_complete" ) )
            ee_tracker_highrise_signal_once( "floor_symbols", "bo2.highrise.shared.floor_symbols" );

        if ( stage == "slb" )
            ee_tracker_highrise_emit_ball_progress();

        elevator_count = int( flag( "sq_atd_elevator0" ) ) + int( flag( "sq_atd_elevator1" ) ) + int( flag( "sq_atd_elevator2" ) ) + int( flag( "sq_atd_elevator3" ) );

        if ( elevator_count != level.ee_tracker_highrise_elevator_progress )
        {
            level.ee_tracker_highrise_elevator_progress = elevator_count;
            ee_tracker_highrise_progress( "bo2.highrise.elevator_progress", elevator_count, 4 );
        }

        players = get_players();

        for ( i = 0; i < players.size; i++ )
            players[i] thread ee_tracker_highrise_profile( i );

        if ( !level.ee_tracker_highrise_route_locked && flag( "sq_ric_tower_complete" ) )
            ee_tracker_highrise_select_route( "richtofen" );
        else if ( !level.ee_tracker_highrise_route_locked && flag( "sq_max_tower_complete" ) )
            ee_tracker_highrise_select_route( "maxis" );

        wait 1;
    }
}

ee_tracker_highrise_profile( player_slot )
{
    player = self;
    last_completed = player maps\mp\zombies\_zm_stats::get_global_stat( "sq_highrise_last_completed" );
    rich_complete = player maps\mp\zombies\_zm_stats::get_global_stat( "sq_highrise_rich_complete" );
    maxis_complete = player maps\mp\zombies\_zm_stats::get_global_stat( "sq_highrise_maxis_complete" );
    navcard = player maps\mp\zombies\_zm_stats::get_global_stat( "navcard_applied_zm_highrise" );
    signature = "" + last_completed + ":" + rich_complete + ":" + maxis_complete + ":" + navcard;

    if ( isdefined( player.ee_tracker_highrise_profile_signature ) && player.ee_tracker_highrise_profile_signature == signature )
        return;

    player.ee_tracker_highrise_profile_signature = signature;
    printf( "[EETrackerT6] {\"schemaVersion\":1,\"type\":\"player_state\",\"game\":\"bo2\",\"map\":\"zm_highrise\",\"sessionId\":\"" + level.ee_tracker_highrise_session + "\",\"playerSlot\":" + player_slot + ",\"lastCompletedSide\":" + last_completed + ",\"richtofenCompletionCount\":" + rich_complete + ",\"maxisCompletionCount\":" + maxis_complete + ",\"navcardAppliedCount\":" + navcard + ",\"source\":\"gsc\"}\n" );
}

ee_tracker_highrise_watch_complete()
{
    level endon( "end_game" );
    level waittill( "highrise_sidequest_achieved" );

    if ( !level.ee_tracker_highrise_route_locked )
    {
        if ( flag( "sq_ric_tower_complete" ) )
            ee_tracker_highrise_select_route( "richtofen" );
        else if ( flag( "sq_max_tower_complete" ) )
            ee_tracker_highrise_select_route( "maxis" );
    }

    ee_tracker_highrise_signal( "bo2.highrise.final.complete" );
}

ee_tracker_highrise_select_route( route )
{
    if ( level.ee_tracker_highrise_route_locked )
        return;

    level.ee_tracker_highrise_route_locked = 1;
    ee_tracker_highrise_path( route );

    if ( route == "richtofen" )
    {
        ee_tracker_highrise_signal( "bo2.highrise.richtofen.ssp" );
        ee_tracker_highrise_signal( "bo2.highrise.richtofen.pts" );
    }
    else
    {
        ee_tracker_highrise_signal( "bo2.highrise.maxis.ssp" );
        ee_tracker_highrise_signal( "bo2.highrise.maxis.pts" );
    }
}

ee_tracker_highrise_stage_complete( stage )
{

}

ee_tracker_highrise_signal_once( key, signal )
{
    if ( key == "elevators" )
    {
        if ( isdefined( level.ee_tracker_highrise_elevators_seen ) )
            return;

        level.ee_tracker_highrise_elevators_seen = 1;
    }
    else
    {
        if ( isdefined( level.ee_tracker_highrise_floor_symbols_seen ) )
            return;

        level.ee_tracker_highrise_floor_symbols_seen = 1;
    }

    ee_tracker_highrise_signal( signal );
}

ee_tracker_highrise_progress( signal, progress, maximum )
{
    printf( "[EETrackerT6] {\"schemaVersion\":1,\"type\":\"quest_progress\",\"game\":\"bo2\",\"map\":\"zm_highrise\",\"sessionId\":\"" + level.ee_tracker_highrise_session + "\",\"signal\":\"" + signal + "\",\"progress\":" + progress + ",\"progressMax\":" + maximum + ",\"source\":\"gsc\"}\n" );
}

ee_tracker_highrise_emit_ball_progress()
{
    balls = getentarray( "sq_dragon_lion_ball", "targetname" );
    remaining = 0;

    for ( i = 0; i < balls.size; i++ )
        if ( isdefined( balls[i] ) )
            remaining++;

    level.ee_tracker_highrise_ball_stage_seen = 1;
    destroyed = 2 - remaining;
    destroyed = int( max( 0, min( 2, destroyed ) ) );

    if ( destroyed != level.ee_tracker_highrise_ball_progress )
    {
        level.ee_tracker_highrise_ball_progress = destroyed;
        ee_tracker_highrise_progress( "bo2.highrise.dragon_balls_progress", destroyed, 2 );
    }

    if ( remaining == 0 && level.ee_tracker_highrise_ball_stage_seen )
        ee_tracker_highrise_signal_once( "dragon_balls", "bo2.highrise.shared.dragon_balls" );
}

ee_tracker_highrise_path( route )
{
    printf( "[EETrackerT6] {\"schemaVersion\":1,\"type\":\"quest_path_selected\",\"game\":\"bo2\",\"map\":\"zm_highrise\",\"sessionId\":\"" + level.ee_tracker_highrise_session + "\",\"signalValue\":\"" + route + "\",\"source\":\"gsc\"}\n" );
}

ee_tracker_highrise_signal( signal )
{
    printf( "[EETrackerT6] {\"schemaVersion\":1,\"type\":\"quest_signal\",\"game\":\"bo2\",\"map\":\"zm_highrise\",\"sessionId\":\"" + level.ee_tracker_highrise_session + "\",\"signal\":\"" + signal + "\",\"source\":\"gsc\"}\n" );
}
