// T6 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool
#include common_scripts\utility;
#include maps\mp\_utility;

main()
{
    printf( "[EETrackerT6] {\"schemaVersion\":1,\"type\":\"observer_loaded\",\"game\":\"bo2\",\"map\":\"zm_tomb\",\"source\":\"gsc\"}\n" );
}

init()
{
    level thread ee_tracker_tomb_monitor();
    level thread ee_tracker_tomb_watch_inventory();
}

ee_tracker_tomb_watch_inventory()
{
    level endon( "end_game" );
    level.ee_tracker_inventory_signatures = [];

    while ( true )
    {
        players = get_players();

        for ( i = 0; i < players.size; i++ )
            players[i] thread ee_tracker_tomb_inventory_if_changed( i );

        wait 1;
    }
}

ee_tracker_tomb_inventory_if_changed( slot )
{
    items = "";
    weapons = self getweaponslist();

    for ( i = 0; i < weapons.size; i++ )
    {
        if ( weapons[i] == "staff_air_zm" || weapons[i] == "staff_air_upgraded_zm" || weapons[i] == "staff_fire_zm" || weapons[i] == "staff_fire_upgraded_zm" || weapons[i] == "staff_lightning_zm" || weapons[i] == "staff_lightning_upgraded_zm" || weapons[i] == "staff_water_zm" || weapons[i] == "staff_water_upgraded_zm" || weapons[i] == "equip_dieseldrone_zm" )
            items = items + weapons[i] + "|";
    }

    if ( self hasweapon( "equip_dieseldrone_zm" ) )
        items = items + "equip_dieseldrone_zm|";

    tactical = self get_player_tactical_grenade();

    if ( isdefined( tactical ) && tactical == "beacon_zm" )
        items = items + tactical + "|";

    if ( isdefined( level.ee_tracker_inventory_signatures[slot] ) && level.ee_tracker_inventory_signatures[slot] == items )
        return;

    level.ee_tracker_inventory_signatures[slot] = items;
    printf( "[EETrackerT6] {\"schemaVersion\":1,\"type\":\"player_inventory\",\"game\":\"bo2\",\"map\":\"zm_tomb\",\"sessionId\":\"" + level.ee_tracker_tomb_session + "\",\"playerSlot\":" + slot + ",\"inventoryItems\":\"" + items + "\",\"source\":\"gsc\"}\n" );
}

ee_tracker_tomb_monitor()
{
    level endon( "end_game" );
    level.ee_tracker_tomb_session = randomint( 1000000000 );
    level.ee_tracker_tomb_step = -1;
    level.ee_tracker_tomb_archangel_reported = 0;
    printf( "[EETrackerT6] {\"schemaVersion\":1,\"type\":\"session_started\",\"game\":\"bo2\",\"map\":\"zm_tomb\",\"sessionId\":\"" + level.ee_tracker_tomb_session + "\",\"source\":\"gsc\"}\n" );

    while ( true )
    {
        if ( isdefined( level.n_ee_step ) && level.n_ee_step != level.ee_tracker_tomb_step )
        {
            previous_step = level.ee_tracker_tomb_step;
            level.ee_tracker_tomb_step = level.n_ee_step;

            if ( level.n_ee_step > 0 && level.n_ee_step <= 8 )
                ee_tracker_tomb_signal( "bo2.origins.step_" + level.n_ee_step + ".started" );

            if ( previous_step > 0 && previous_step <= 8 )
                ee_tracker_tomb_signal( "bo2.origins.step_" + previous_step + ".complete" );
        }

        if ( flag( "ee_all_staffs_crafted" ) )
            ee_tracker_tomb_once( "crafted", "bo2.origins.staffs_crafted" );

        if ( flag( "ee_samantha_released" ) )
            ee_tracker_tomb_once( "released", "bo2.origins.complete" );

        if ( !level.ee_tracker_tomb_archangel_reported && isdefined( level.found_ee_radio_count ) && level.found_ee_radio_count >= 3 )
        {
            level.ee_tracker_tomb_archangel_reported = 1;
            ee_tracker_tomb_emit_side_egg_step( "shepherd_of_fire", 0 );
            ee_tracker_tomb_emit_side_egg_step( "shepherd_of_fire", 1 );
            ee_tracker_tomb_emit_side_egg_step( "shepherd_of_fire", 2 );
            ee_tracker_tomb_signal( "bo2.origins.shepherd_of_fire.complete" );
        }

        wait 1;
    }
}

ee_tracker_tomb_once( key, signal )
{
    if ( key == "crafted" )
    {
        if ( isdefined( level.ee_tracker_tomb_seen_crafted ) )
            return;

        level.ee_tracker_tomb_seen_crafted = 1;
    }
    else
    {
        if ( isdefined( level.ee_tracker_tomb_seen_released ) )
            return;

        level.ee_tracker_tomb_seen_released = 1;
    }

    ee_tracker_tomb_signal( signal );
}

ee_tracker_tomb_signal( signal )
{
    printf( "[EETrackerT6] {\"schemaVersion\":1,\"type\":\"quest_signal\",\"game\":\"bo2\",\"map\":\"zm_tomb\",\"sessionId\":\"" + level.ee_tracker_tomb_session + "\",\"signal\":\"" + signal + "\",\"source\":\"gsc\"}\n" );
}

ee_tracker_tomb_emit_side_egg_step( egg_id, step_index )
{
    printf( "[EETrackerT6] {\"schemaVersion\":1,\"type\":\"side_egg_step\",\"game\":\"bo2\",\"map\":\"zm_tomb\",\"eggId\":\"" + egg_id + "\",\"stepIndex\":" + step_index + ",\"source\":\"gsc\"}\n" );
}
